---
  - hosts: all
    tasks:
    
    - name: Install required system packages
      ansible.builtin.apt:
        update_cache: yes
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
        state: latest

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg
        state: present

    - name: Add Docker repo
      ansible.builtin.apt_repository:
        filename: "docker-repo"
        repo: deb https://download.docker.com/linux/{{ansible_distribution | lower}} {{ansible_distribution_release}} stable
        state: present

    - name: Update apt and install docker
      ansible.builtin.apt:
        update_cache: yes
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
        state: latest

    - name: Update apt and install docker
      ansible.builtin.apt:
        update_cache: yes
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
        state: latest

